const images = {
    table: require('../assets/img/table.png'),
    tab: require('../assets/img/tab.png'),
    tables: require('../assets/img/stols.png'),
    tablesFive: require('../assets/img/tableFive.png'),
    all_bg: require('../assets/img/all_bg.png'),
    card: require('../assets/img/card.png'),
    // cash: require('../assets/img/cash.png'),
    game: require('../assets/img/game.png'),
    // help: require('../assets/img/help.png'),
    logout: require('../assets/img/logout.png'),
    // messages: require('../assets/img/messages.png'),
    // news: require('../assets/img/news.png'),
    // people: require('../assets/img/people.png'),
    // setting: require('../assets/img/setting.png'),
    unselected: require('../assets/img/Unselected.png'),
    bg_card: require('../assets/img/bg_2.png'),
    bitcoin: require('../assets/img/bitcoin.png'),
    // profile: require('../assets/img/profile.png'),
    addp: require('../assets/img/addp.png'),
    back: require('../assets/img/back.png'),
    edit: require('../assets/img/edit.png'),
    news_bg: require('../assets/img/bg_news.png'),
    // poker_table: require('../assets/img/poker_table.png'),
    // diler: require('../assets/img/diler.png'),
    // close_cards: require('../assets/img/close_cards.png'),
    save_table: require('../assets/img/save_table.png'),
    table_lobby: require('../assets/img/save_table.png'),
    minus: require('../assets/img/minus.png'),
    plus: require('../assets/img/plus.png'),
    menu_btn: require('../assets/img/menu.png'),
    stul: require('../assets/img/st.png'),
    // stul1: require('../assets/img/stuli1.png'),
    // stul2: require('../assets/img/stuli2.png'),
    // stul3: require('../assets/img/stuli3.png'),
    // stul4: require('../assets/img/stuli4.png'),
    // stul5: require('../assets/img/stuli5.png'),
    // stul6: require('../assets/img/stuli6.png'),
    // stul7: require('../assets/img/stuli7.png'),
    // stul8: require('../assets/img/stuli8.png'),
    // stul9: require('../assets/img/stuli9.png'),
    redCard: require('../assets/img/red.png'),
    soundMuted: require('../assets/img/sound-d.png'),
    soundMax: require('../assets/img/sound-u.png'),
    sliderHandler: require('../assets/img/slider-icon.png'),
    logo: require('../assets/img/logo.png'),
    up: require('../assets/img/up.png'),
    down: require('../assets/img/down.png'),
};

export default images;
